
# Global definitions

# Host
http://localhost:8080/e-commerce-back-end

# CURL options
-i
-s

# Headers
Content-Type: application/json; charset=utf-8
User-Agent: VRC
Accept: application/json

#Variable declarations
#id = 1

--
# End of global definitions



# Permission resource


# Get all permission resources
--
GET /permissions


# Get a single permission resource
--
GET /permissions/34


# Create a permission resource
--
POST /permissions
{ 
	"name": "New Permission Here",
	"description": "The new permission description"
}

# Update a permission resource
--
PUT /permissions/53
{
	"name": "New Permission 53",
	"description": "The new permission description"
}

# Delete permission resource
--
DELETE /permissions/24





