
# Global definitions

# Host
http://localhost:8080/e-commerce-back-end

# CURL options
-i
-s

# Headers
Content-Type: application/json; charset=utf-8
User-Agent: VRC
Accept: application/json

--
# End of global definitions


--
GET /permissions


--
GET /permissions/24


--
POST /permissions
{ 
	"name": "New Permission Here",
	"description": "The new permission description"
}

--
PUT /permissions/53
{
	"name": "New Permission 53",
	"description": "The new permission description"
}

--
DELETE /permissions/1




